accessing
exception: anException
    self exception: anException process: nil