tests
testError
  1 perform: #'foo'