tests
testError2
  1 perform: #'foo'